remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: WikiDBs
logo: Logo.png
image:
  teaser: Logo.png
description: A corpus of relational databases.
show_downloads: false
